### ISSUE TITLE
Spacing between logo and package name

### ISSUE THREAD

**Issue by pat-s** [cynkra/cynkratemplate#34]
Looks a bit small. Should we increase it?

Instead of a 5px padding (current state) a padding of 20px looks decent?

```css
#cynkra-logo-nav {
    height: 25px;
    padding-right: 20px;
    padding-bottom: 2px;
}
```

I also feel that a slight left padding (e.g. 2px) to the logo in the footer would smoothen things a bit.

```css
#cynkra-logo-footer {
    height: 20px;
    padding-bottom: 2px;
    padding-left: 2px;
}
```
